scanbooth_web/config/routes.rb
ScanBooth::Application.routes.draw do

  match "admin" => 'admin#index'
  get "admin/index"

  get "welcome/index"

  get "welcome/thanks"

  resources :users do
    member do
      get 'upload_and_mail'
    end
  end

  root :to => 'welcome#index'

  mount Resque::Server.new, :at => "/resque"
end

scanbooth_web/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :scan_file, :mailed, :printed, :external_view_id, :external_download_id
  before_create :generate_filename
  after_create :async_upload_model

  def generate_filename
    self.scan_file = self.name.gsub(/[^a-z0-9\\-]/i,'')
    self.scan_file = self.id if self.scan_file.blank?;
  end

  def scan_file_with_ext
    [self.scan_file, ScanBooth::Application.config.scan_extension].join('.')
  end

  def unique_file_with_ext
    [self.scan_file, self.created_at.strftime('%Y-%m-%d-%H%M%S')].join('_')
  end

  def async_upload_model
    Resque.enqueue(SketchfabUpload, self.id) if ScanBooth::Application.config.scan_viewer_enabled
    Resque.enqueue(FtpUpload, self.id) if ScanBooth::Application.config.scan_download_enabled
  end
end

scanbooth_web/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

scanbooth_web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

scanbooth_web/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # GET /users/1/upload_and_mail
  def upload_and_mail
    @user = User.find(params[:id])
    @user.async_upload_model
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Thank You! We'll be in touch when your scan is ready!" }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

scanbooth_web/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.new
  end

  def thanks
  end
end

scanbooth_web/app/helpers/admin_helper.rb
module AdminHelper
end

scanbooth_web/app/helpers/application_helper.rb
module ApplicationHelper
end

scanbooth_web/app/helpers/users_helper.rb
module UsersHelper
end

scanbooth_web/app/helpers/welcome_helper.rb
module WelcomeHelper
end

scanbooth_web/app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

scanbooth_web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScanBooth</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

scanbooth_web/app/views/users/_admin_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :scan_file %><br />
    <%= f.text_field :scan_file %>
  </div>
  <div class="field">
    <%= f.label :external_view_id %><br />
    <%= f.text_field :external_view_id %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

scanbooth_web/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :printed %><br />
    <%= f.check_box :printed %>
  </div>
  <div class="field">
    <%= f.label :mailed %><br />
    <%= f.check_box :mailed %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

scanbooth_web/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

scanbooth_web/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Scan file</th>
    <th>External View Id</th>
    <th>External Download Id</th>
    <th>Printed</th>
    <th>Mailed</th>
    <th>Actions</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.scan_file %></td>
    <td><%= user.external_view_id %></td>
    <td><%= user.external_download_id %></td>
    <td><%= user.printed %></td>
    <td><%= user.mailed %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Upload and Mail', upload_and_mail_user_path(user) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

scanbooth_web/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

scanbooth_web/app/views/users/scan_processed.html.erb
<p>
  <b>Hopefully the files are being uploaded right now.</b>
  <%= @user.name %>
  <%= @user.email %>
  <%= @user.scan_file %>
</p>

scanbooth_web/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Scanned at:</b>
  <%= @user.created_at %>
</p>

<p class="filename">
  <%= @user.scan_file %>
</p>

<%= link_to 'New Scan', welcome_index_path %>

scanbooth_web/app/views/welcome/index.html.erb
<h1>Get 3D Scanned</h1>
<p>Thanks for stopping by our booth!</p>

<p>Please fill out this form so that we can send you your 3D scan.</p>

<%= render 'users/form' %>

scanbooth_web/app/views/welcome/thanks.html.erb
<h1>Welcome#thanks</h1>
<p>Find me in app/views/welcome/thanks.html.erb</p>